name: macOS tests

on:
  workflow_dispatch:
  push:
    branches:
      - maintenance/**
      - main
  pull_request:
    branches:
      - main
      - maintenance/**

permissions:
   contents: read  # to fetch code (actions/checkout)

env:
  INSTALLDIR: "build-install"
  CCACHE_DIR: "${{ github.workspace }}/.ccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml

  test_meson:
    name: Conda & umfpack/scikit-sparse, fast, py3.11/npAny, spin
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Ccache
      run: brew install ccache

    - name: Prepare compiler cache
      id: prep-ccache
      shell: bash -l {0}
      run: |
        mkdir -p "${CCACHE_DIR}"
        echo "dir=$CCACHE_DIR" >> $GITHUB_OUTPUT
        NOW=$(date -u +"%F-%T")
        echo "timestamp=${NOW}" >> $GITHUB_OUTPUT

    - name: Setup compiler cache
      uses: actions/cache@v4
      id: cache-ccache
      with:
        path: ${{ steps.prep-ccache.outputs.dir }}
        key:  ${{ github.workflow }}-${{ matrix.python-version }}-ccache-macos-${{ steps.prep-ccache.outputs.timestamp }}
        restore-keys: |
          ${{ github.workflow }}-${{ matrix.python-version }}-ccache-macos-

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: true
        activate-environment: scipy-dev
        use-only-tar-bz2: false
        miniforge-variant: Miniforge3
        miniforge-version: latest
        use-mamba: true

    - name: Cache conda
      uses: actions/cache@v4
      id: envcache
      env:
        CACHE_NUMBER: 1
      with:
        path: ${{ env.CONDA }}/envs/scipy-dev
        key: ${{ runner.os }}--conda-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: Update Conda Environment
      if: steps.envcache.outputs.cache-hit != 'true'
      run: mamba env update -n scipy-dev -f environment.yml

    - name: Build and Install SciPy
      shell: bash -l {0}
      run: |
        conda activate scipy-dev
        mamba install python=${{ matrix.python-version }}
        mamba install "scikit-umfpack=0.3.3" scikit-sparse libboost-headers=1.89.0 qhull=2020.2
        export BOOST_INCLUDEDIR=${{ env.CONDA }}/envs/scipy-dev/include/boost
        export BOOST_LIBRARYDIR=${{ env.CONDA }}/envs/scipy-dev/lib
        rm -rf subprojects/boost_math
        rm -rf subprojects/qhull_r
        CC="ccache $CC" spin build --use-system-libraries

    - name: Install pytest-testmon
      shell: bash -l {0}
      run: |
        conda activate scipy-dev
        pip install pytest-testmon

    - name: Cache testmon data
      uses: actions/cache@v4
      with:
        path: .testmondata
        key: testmon-${{ github.workflow }}-${{ github.ref_name }}-${{ matrix.python-version }}
        restore-keys: |
          testmon-${{ github.workflow }}-${{ github.ref_name }}-

    - name: Test SciPy (with testmon on PRs, full on main)
      shell: bash -l {0}
      run: |
        conda activate scipy-dev
        export OMP_NUM_THREADS=2
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          spin test -j2
        else
          spin test -- --testmon -j2
        fi

    - name: Ccache statistics
      shell: bash -l {0}
      run: ccache -s

  test_scipy_openblas:
    name: M1 & OpenBLAS, fast, py3.11/npAny, spin
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
    runs-on: macos-14
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Build and Install SciPy
      run: |
        sudo xcode-select -s /Applications/Xcode_15.2.app
        git submodule update --init
        GFORTRAN_LOC=$(which gfortran-13)
        ln -s $GFORTRAN_LOC gfortran
        export PATH=$PWD:$PATH
        GFORTRAN_LIB=$(dirname `gfortran --print-file-name libgfortran.dylib`)
        export DYLD_LIBRARY_PATH=$GFORTRAN_LIB
        pip install meson cython pythran pybind11 ninja numpy spin "click<8.3.0"
        pip install -r requirements/openblas.txt
        spin build --with-scipy-openblas
        pip install pooch pytest hypothesis pytest-testmon

    - name: Cache testmon data
      uses: actions/cache@v4
      with:
        path: .testmondata
        key: testmon-${{ github.workflow }}-${{ github.ref_name }}-${{ matrix.python-version }}
        restore-keys: |
          testmon-${{ github.workflow }}-${{ github.ref_name }}-

    - name: Run the test suite (with testmon on PRs, full on main)
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          spin test
        else
          spin test -- --testmon
        fi

  test_accelerate:
    name: Accelerate, full, py3.13/npAny, spin
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        blas-interface: ["LP64", "ILP64"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Make gfortran-13 on runner image usable
      run: |
        FC=$(which gfortran-13)
        GFORTRAN_LIB=$(dirname `$FC --print-file-name libgfortran.dylib`)
        echo DYLD_LIBRARY_PATH=$GFORTRAN_LIB >> "$GITHUB_ENV"
        echo FC=$FC >> "$GITHUB_ENV"

    - name: Install dependencies from PyPI
      run: |
        pip install meson cython pythran pybind11 ninja numpy spin pooch pytest hypothesis "click<8.3.0" pytest-testmon

    - name: Cache testmon data
      uses: actions/cache@v4
      with:
        path: .testmondata
        key: testmon-${{ github.workflow }}-${{ github.ref_name }}-py3.13-${{ matrix.blas-interface }}
        restore-keys: |
          testmon-${{ github.workflow }}-${{ github.ref_name }}-

    - name: Build SciPy with Accelerate (LP64)
      if: matrix.blas-interface == 'LP64'
      run: |
        spin build --with-accelerate -S-Db_ndebug=true

    - name: Build SciPy with Accelerate (ILP64)
      if: matrix.blas-interface == 'ILP64'
      run: |
        spin build -S-Dblas=accelerate -S-Duse-ilp64=true -S-Dblas-symbol-suffix='$NEWLAPACK$ILP64' -S-Db_ndebug=true

    - name: Run the test suite (with testmon on PRs, full on main)
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          spin test -m full
        else
          spin test -- --testmon -m full
        fi
